name: Verificacion

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Dar permisos al Maven Wrapper
        run: chmod +x mvnw

      - name: Ejecutar pruebas
        run: ./mvnw clean verify